# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '登录界面.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import Accounts_DB
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QLineEdit
import resource


class Ui_login(object):

    switch_window = QtCore.pyqtSignal()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1510, 738)
        MainWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        MainWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 160, 350, 490))
        self.label.setStyleSheet("border-image:url(:/images/images/evgeny-tchebotarev-aiwuLjLPFnU-unsplash.jpg);\n"
                                 "border-top-left-radius:30px;\n"
                                 "border-bottom-left-radius:30px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(430, 160, 491, 491))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                   "border-top-right-radius:30px;\n"
                                   "border-bottom-right-radius:30px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(590, 230, 174, 41))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("#pushButton{\n"
                                      "    border:none;\n"
                                      "}\n"
                                      "#pushButton:focus{\n"
                                      "    color: rgb(186, 186, 186);\n"
                                      "}")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        # 登录界面
        self.pushButton.clicked.connect(self.change_widget2)
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("#pushButton_2{\n"
                                        "    border:none;\n"
                                        "}\n"
                                        "#pushButton_2:focus{\n"
                                        "    color: rgb(186, 186, 186);\n"
                                        "}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        # 注册界面
        self.pushButton_2.clicked.connect(self.change_widget3)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(450, 280, 451, 361))
        self.widget_2.setObjectName("widget_2")
        self.lineEdit = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit.setGeometry(QtCore.QRect(20, 20, 411, 71))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("border:1px solid  rgb(0, 0, 0);\n"
                                    "border-radius:8px;")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(20, 120, 411, 71))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("border:1px solid  rgb(0, 0, 0);\n"
                                      "border-radius:8px;")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 260, 401, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("#pushButton_3{\n"
                                        "    background-color: rgb(0, 0, 0);\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    border:3px solid rgb(0,0,0);\n"
                                        "    border-radius:8px;\n"
                                        "}\n"
                                        "#pushButton_3:hover{\n"
                                        "    background-color: rgb(255, 255, 255);\n"
                                        "    color: rgb(0, 0, 0);\n"
                                        "}\n"
                                        "#pushButton_3:pressed{\n"
                                        "    padding-top:5px;\n"
                                        "    padding-left:5px;\n"
                                        "\n"
                                        "}")
        self.pushButton_3.setObjectName("pushButton_3")
        # 登录按钮实现方法
        self.pushButton_3.clicked.connect(self.show1)
        self.checkBox = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox.setGeometry(QtCore.QRect(40, 210, 121, 31))
        self.checkBox.setObjectName("checkBox")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(535, 180, 290, 45))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("")
        self.label_3.setObjectName("label_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(870, 160, 51, 51))
        self.pushButton_4.setStyleSheet("border:none;")
        self.pushButton_4.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon)
        self.pushButton_4.setObjectName("pushButton_4")
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setGeometry(QtCore.QRect(450, 270, 451, 361))
        self.widget_3.setObjectName("widget_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget_3)
        self.lineEdit_3.setGeometry(QtCore.QRect(20, 20, 411, 71))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("border:1px solid  rgb(0, 0, 0);\n"
                                      "border-radius:8px;")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget_3)
        self.lineEdit_4.setGeometry(QtCore.QRect(20, 110, 411, 71))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("border:1px solid  rgb(0, 0, 0);\n"
                                      "border-radius:8px;")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget_3)
        self.lineEdit_5.setGeometry(QtCore.QRect(20, 200, 411, 71))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setStyleSheet("border:1px solid  rgb(0, 0, 0);\n"
                                      "border-radius:8px;")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 290, 401, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("#pushButton_5{\n"
                                        "    background-color: rgb(0, 0, 0);\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    border:3px solid rgb(0,0,0);\n"
                                        "    border-radius:8px;\n"
                                        "}\n"
                                        "#pushButton_5:hover{\n"
                                        "    background-color: rgb(255, 255, 255);\n"
                                        "    color: rgb(0, 0, 0);\n"
                                        "}\n"
                                        "#pushButton_5:pressed{\n"
                                        "    padding-top:5px;\n"
                                        "    padding-left:5px;\n"
                                        "\n"
                                        "}")
        self.pushButton_5.setObjectName("pushButton_5")
        # 注册按钮实现方法
        self.pushButton_5.clicked.connect(self.show2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.label.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25, xOffset=0, yOffset=0))
        self.label_2.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25, xOffset=0, yOffset=0))
        self.pushButton_3.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25, xOffset=3, yOffset=3))
        self.pushButton_5.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25, xOffset=3, yOffset=3))
        self.retranslateUi(MainWindow)

        # 定义按钮4关闭窗口
        self.pushButton_4.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "登录"))
        self.pushButton_2.setText(_translate("MainWindow", "注册"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", " 账号："))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", " 密码："))
        self.pushButton_3.setText(_translate("MainWindow", "登录"))
        self.checkBox.setText(_translate("MainWindow", "记住密码"))
        self.label_3.setText(
            _translate("MainWindow", "<html><head/><body><p align=\"center\">停车场管理系统</p></body></html>"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", " 输入账号："))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", " 设置密码："))
        self.lineEdit_4.setEchoMode(QLineEdit.Password) # 隐藏字
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow", " 确认密码："))
        self.lineEdit_5.setEchoMode(QLineEdit.Password) # 隐藏字
        self.pushButton_5.setText(_translate("MainWindow", "注册"))

    # 注册窗口
    def change_widget3(self):
        self.widget_2.hide()
        self.widget_3.show()

    # 登录窗口
    def change_widget2(self):
        self.widget_3.hide()
        self.widget_2.show()

    # pushButtom_3:获取登录信息+打开主控界面
    def show1(self):
        adm = "zero"
        acc = self.lineEdit.text()
        pa = self.lineEdit_2.text()
        a = Accounts_DB.login_db(adm, acc, pa)
        if a == 1:
            self.switch_window.emit()
        else:
            self.lineEdit_2.setText("")
            self.lineEdit_2.setPlaceholderText(QtCore.QCoreApplication.translate("MainWindow", " 账户或密码输入错误"))

    # pushButtom_5:获取注册信息+打开主控界面
    def show2(self):
            Accounts_DB.create_account_db('zero')
            adm = "zero"
            name = self.lineEdit_3.text()
            code = self.lineEdit_4.text()
            is_super = "0"
            b = self.lineEdit_5.text()
            c = self.lineEdit_4.text()
            if b == c:
                Accounts_DB.insert(adm, name, code, is_super)
                self.lineEdit_5.setText("")
                self.lineEdit_5.setPlaceholderText(QtCore.QCoreApplication.translate("MainWindow", " 注册成功！请去登录界面"))
            else:
                self.lineEdit_5.setText("")
                self.lineEdit_5.setPlaceholderText(QtCore.QCoreApplication.translate("MainWindow", " 请重新输入："))

